"""`spritekit compile`: turns everything under `assets/` into
`crates/vpet-core/src/assets/generated.rs`. See docs/CONTENT.md and docs/adr/0009. Refuses to
emit if any validator error remains, or (by default) if any species pose is missing from
`assets/approved.lock` or has changed since it was approved.

Sprites are emitted as inline byte-array literals (`Sprite { w, h, rows: &[0x.., ..] }`) rather
than named `static`s: Rust promotes a `&[u8]` array literal inside a `static`/`const` initializer
to `'static` automatically, so there's no need to invent a unique Rust identifier per pose —
which matters because font glyph names like "0".."9" aren't valid Rust identifiers anyway.
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path

from .approve import unapproved_or_changed_poses
from .grid import bbox as compute_bbox, pack_image, pack_mask, parse
from .spec import Spec
from .validate import validate_all

HEADER = """\
// GENERATED by `spritekit compile` from assets/ (see docs/CONTENT.md, docs/adr/
// 0009-assets-compiled-in-checked-in-codegen.md). Do not hand-edit: edit the text grids or
// species.toml under assets/ and run `spritekit compile` again. CI runs `spritekit compile
// --check` to keep this file honest.

use crate::assets::{{GameRules, Pose, Sprite, SpeciesDef, StageRules, StageSet}};

pub const CONTENT_HASH: u32 = 0x{content_hash:08x};
"""


class CompileError(Exception):
    pass


def _fnv1a(data: bytes) -> int:
    h = 0x811C9DC5
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


@dataclass
class Emitter:
    hash_input: bytearray = field(default_factory=bytearray)

    def rust_bytes(self, data: bytes) -> str:
        self.hash_input.extend(data)
        return "&[" + ", ".join(f"0x{b:02X}" for b in data) + "]"

    def sprite_literal(self, sprite, w: int, h: int) -> str:
        img = pack_image(sprite.rows, w)
        return f"Sprite {{ w: {w}, h: {h}, rows: {self.rust_bytes(img)} }}"

    def pose_literal(self, sprite, w: int, h: int, default_mouth) -> str:
        img = pack_image(sprite.rows, w)
        mask = pack_mask(sprite.rows, w)
        bb = compute_bbox(sprite.rows, w, h)
        mouth = sprite.mouth if sprite.mouth is not None else default_mouth(bb)
        blink = (
            f"Some(Sprite {{ w: {w}, h: {h}, rows: {self.rust_bytes(mask)} }})"
            if mask is not None
            else "None"
        )
        bbox_str = f"({bb[0]}, {bb[1]}, {bb[2]}, {bb[3]})" if bb else "(0, 0, 0, 0)"
        return (
            f"Pose {{ img: Sprite {{ w: {w}, h: {h}, rows: {self.rust_bytes(img)} }}, "
            f"blink: {blink}, mouth: ({mouth[0]}, {mouth[1]}), bbox: {bbox_str} }}"
        )


def _default_mouth(bb) -> tuple[int, int]:
    """docs/art/SPRITE_FORMAT.md's default: leftmost on-pixel at 60% bbox height. Callers only
    reach this for poses without an explicit `@mouth` header; a reasonable fallback when there
    is no bbox at all (a blank pose) is the cell centre-ish, which nothing should ever render."""
    if bb is None:
        return (7, 9)
    x0, y0, x1, y1 = bb
    y = round(y0 + 0.6 * (y1 - y0))
    return (x0, y)


def _load_global(assets_root: Path, name: str):
    f = assets_root / "global" / f"{name}.txt"
    return parse(str(f), f.read_text(encoding="utf-8"))


def _species_toml(species_dir: Path) -> dict:
    with open(species_dir / "species.toml", "rb") as f:
        return tomllib.load(f)


def _stage_rules(stage_toml: dict) -> str:
    lo, hi = stage_toml.get("poop_interval_secs", [7200, 10800])
    stage_secs = stage_toml.get("stage_secs", 0)
    return (
        f"StageRules {{ hunger_step_secs: {stage_toml['hunger_step_secs']}, "
        f"happy_step_secs: {stage_toml['happy_step_secs']}, "
        f"poop_interval_min_secs: {lo}, poop_interval_max_secs: {hi}, "
        f"stage_secs: {stage_secs} }}"
    )


def _compile_stage_set(em: Emitter, gf, stage_toml: dict) -> str:
    by_name = {s.name: s for s in gf.sprites}

    def pose(name: str) -> str:
        s = by_name[name]
        return em.pose_literal(s, gf.cell_w, gf.cell_h, _default_mouth)

    def optional_pose(name: str) -> str:
        s = by_name.get(name)
        return "None" if s is None else f"Some({em.pose_literal(s, gf.cell_w, gf.cell_h, _default_mouth)})"

    required = ["idle_a", "idle_b", "happy", "eat", "sleep"]
    missing = [p for p in required if p not in by_name]
    if missing:
        raise CompileError(f"{gf.path}: missing required pose(s): {missing}")

    return (
        "StageSet {\n"
        f"    idle_a: {pose('idle_a')},\n"
        f"    idle_b: {pose('idle_b')},\n"
        f"    happy: {pose('happy')},\n"
        f"    eat: {pose('eat')},\n"
        f"    sleep: {pose('sleep')},\n"
        f"    sad: {optional_pose('sad')},\n"
        f"    attack: {optional_pose('attack')},\n"
        f"    rules: {_stage_rules(stage_toml)},\n"
        "}"
    )


def _compile_species(em: Emitter, assets_root: Path, slug: str) -> str:
    species_dir = assets_root / "species" / slug
    toml = _species_toml(species_dir)
    sp = toml["species"]
    schedule = toml["schedule"]
    assets_cfg = toml.get("assets", {})

    stage_files = {}
    for stage in ("baby", "child", "adult"):
        f = species_dir / f"{stage}.txt"
        stage_files[stage] = parse(str(f), f.read_text(encoding="utf-8"))

    adult_alt_str = "None"
    if assets_cfg.get("adult_alt", False):
        f = species_dir / "adult_alt.txt"
        if not f.is_file():
            raise CompileError(f"{slug}: species.toml declares adult_alt=true but {f} is missing")
        gf = parse(str(f), f.read_text(encoding="utf-8"))
        adult_alt_str = f"Some({_compile_stage_set(em, gf, toml['stages']['adult'])})"

    egg_str = "None"
    if assets_cfg.get("egg_override", False):
        raise CompileError(f"{slug}: egg_override=true is not yet implemented by compile.py")

    return (
        "SpeciesDef {\n"
        f"    id: {sp['id']},\n"
        f'    slug: "{sp["slug"]}",\n'
        f'    name: "{sp["name"]}",\n'
        f"    hatch_secs: {sp['hatch_secs']},\n"
        f"    schedule: ({schedule['awake_secs']}, {schedule['sleep_secs']}),\n"
        f"    egg: {egg_str},\n"
        f"    baby: {_compile_stage_set(em, stage_files['baby'], toml['stages']['baby'])},\n"
        f"    child: {_compile_stage_set(em, stage_files['child'], toml['stages']['child'])},\n"
        f"    adult: {_compile_stage_set(em, stage_files['adult'], toml['stages']['adult'])},\n"
        f"    adult_alt: {adult_alt_str},\n"
        "}"
    )


def _compile_game_rules(spec: Spec) -> str:
    g = spec.data.get("rules", {}).get("game", {})
    sick_lo, sick_hi = g["sick_delay_secs"]
    tant_lo, tant_hi = g["tantrum_interval_secs"]
    return (
        "GameRules {\n"
        f"    care_miss_secs: {g['care_miss_secs']},\n"
        f"    sick_delay_min_secs: {sick_lo},\n"
        f"    sick_delay_max_secs: {sick_hi},\n"
        f"    sick_damage_secs: {g['sick_damage_secs']},\n"
        f"    sick_damage_hp: {g['sick_damage_hp']},\n"
        f"    starve_secs: {g['starve_secs']},\n"
        f"    lifespan_penalty_per_mistake_secs: {g['lifespan_penalty_per_mistake_secs']},\n"
        f"    lifespan_floor_secs: {g['lifespan_floor_secs']},\n"
        f"    tantrum_interval_min_secs: {tant_lo},\n"
        f"    tantrum_interval_max_secs: {tant_hi},\n"
        f"    battle_cooldown_secs: {g['battle_cooldown_secs']},\n"
        f"    menu_timeout_secs: {g['menu_timeout_secs']},\n"
        f"    hungry_threshold: {g['hungry_threshold']},\n"
        f"    sad_threshold: {g['sad_threshold']},\n"
        f"    full_threshold: {g['full_threshold']},\n"
        f"    overweight_threshold: {g['overweight_threshold']},\n"
        f"    max_poops: {g['max_poops']},\n"
        f"    poop_sick_after_secs: {g['poop_sick_after_secs']},\n"
        f"    snacks_before_sick: {g['snacks_before_sick']},\n"
        f"    meal_hunger: {g['meal_hunger']},\n"
        f"    meal_weight: {g['meal_weight']},\n"
        f"    snack_happy: {g['snack_happy']},\n"
        f"    snack_weight: {g['snack_weight']},\n"
        f"    play_weight: {g['play_weight']},\n"
        f"    play_happy_win: {g['play_happy_win']},\n"
        f"    play_happy_lose: {g['play_happy_lose']},\n"
        f"    medicine_health: {g['medicine_health']},\n"
        f"    medicine_discipline_penalty: {g['medicine_discipline_penalty']},\n"
        f"    discipline_gain: {g['discipline_gain']},\n"
        f"    discipline_wrong_happy_penalty: {g['discipline_wrong_happy_penalty']},\n"
        f"    wake_health_bonus: {g['wake_health_bonus']},\n"
        f"    battle_hit_damage: {g['battle_hit_damage']},\n"
        f"    battle_crit_damage: {g['battle_crit_damage']},\n"
        f"    battle_happy_win: {g['battle_happy_win']},\n"
        f"    battle_happy_lose: {g['battle_happy_lose']},\n"
        f"    battle_lose_sick_pct: {g['battle_lose_sick_pct']},\n"
        "}"
    )


def compile_source(assets_root: Path, spec: Spec, allow_unapproved: bool = False) -> str:
    reports = validate_all(assets_root, spec)
    bad = [r for r in reports if not r.ok]
    if bad:
        lines = [f"{r.file}::{r.sprite}: {e}" for r in bad for e in r.errors]
        raise CompileError("validation failed:\n" + "\n".join(lines))

    registry_path = assets_root / "registry.toml"
    registry = tomllib.loads(registry_path.read_text(encoding="utf-8")).get("species", [])

    if not allow_unapproved:
        for entry in registry:
            problems = unapproved_or_changed_poses(assets_root, entry["slug"])
            if problems:
                raise CompileError(
                    f"{entry['slug']}: unapproved poses (run `spritekit approve {entry['slug']}`, "
                    f"or pass --allow-unapproved for a dev build):\n" + "\n".join(problems)
                )

    em = Emitter()

    icons_gf = _load_global(assets_root, "icons")
    icon_names = spec.global_names.get("icons", [])
    icon_by_name = {s.name: s for s in icons_gf.sprites}
    icons_str = ",\n    ".join(
        em.sprite_literal(icon_by_name[n], icons_gf.cell_w, icons_gf.cell_h) for n in icon_names
    )

    egg_gf = _load_global(assets_root, "egg")
    egg_by_name = {s.name: s for s in egg_gf.sprites}
    egg_names = spec.global_names.get("egg", ["egg_a", "egg_b"])
    egg_str = ",\n    ".join(
        em.sprite_literal(egg_by_name[n], egg_gf.cell_w, egg_gf.cell_h) for n in egg_names
    )

    effects_gf = _load_global(assets_root, "effects")
    effect_by_name = {s.name: s for s in effects_gf.sprites}
    effect_names = spec.global_names.get("effects", [])
    effects_str = ",\n    ".join(
        em.sprite_literal(effect_by_name[n], effects_gf.cell_w, effects_gf.cell_h) for n in effect_names
    )

    items_gf = _load_global(assets_root, "items")
    item_by_name = {s.name: s for s in items_gf.sprites}
    item_names = spec.global_names.get("items", [])
    items_str = ",\n    ".join(
        em.sprite_literal(item_by_name[n], items_gf.cell_w, items_gf.cell_h) for n in item_names
    )

    tombstone_gf = _load_global(assets_root, "tombstone")
    tombstone_sprite = tombstone_gf.sprites[0]
    tombstone_str = em.sprite_literal(tombstone_sprite, tombstone_gf.cell_w, tombstone_gf.cell_h)

    hearts_gf = _load_global(assets_root, "hearts")
    heart_by_name = {s.name: s for s in hearts_gf.sprites}
    hearts_str = ",\n    ".join(
        em.sprite_literal(heart_by_name[n], hearts_gf.cell_w, hearts_gf.cell_h)
        for n in ("heart_full", "heart_empty")
    )

    font_gf = _load_global(assets_root, "font3x5")
    font_str = ",\n    ".join(
        em.sprite_literal(s, font_gf.cell_w, font_gf.cell_h) for s in font_gf.sprites
    )
    font_count = len(font_gf.sprites)

    species_strs = [_compile_species(em, assets_root, entry["slug"]) for entry in registry]
    species_array = ",\n".join(species_strs)

    game_rules_str = _compile_game_rules(spec)

    content_hash = _fnv1a(bytes(em.hash_input))

    out = [HEADER.format(content_hash=content_hash)]
    out.append(f"\npub static ICONS: [Sprite; {len(icon_names)}] = [\n    {icons_str},\n];\n")
    out.append(_icon_module(icon_names))
    out.append(f"\npub static EGG: [Sprite; {len(egg_names)}] = [\n    {egg_str},\n];\n")
    out.append(f"\npub static EFFECTS: [Sprite; {len(effect_names)}] = [\n    {effects_str},\n];\n")
    out.append(_effect_module(effect_names))
    out.append(f"\npub static ITEMS: [Sprite; {len(item_names)}] = [\n    {items_str},\n];\n")
    out.append(_item_module(item_names))
    out.append(f"\npub static TOMBSTONE: Sprite = {tombstone_str};\n")
    out.append(f"\npub static HEARTS: [Sprite; 2] = [\n    {hearts_str},\n];\n")
    out.append(
        "pub mod heart {\n    pub const FULL: usize = 0;\n    pub const EMPTY: usize = 1;\n}\n"
    )
    out.append(f"\npub static FONT_3X5: [Sprite; {font_count}] = [\n    {font_str},\n];\n")
    out.append(f"\npub static SPECIES: [SpeciesDef; {len(species_strs)}] = [\n{species_array}\n];\n")
    out.append(f"\npub static GAME: GameRules = {game_rules_str};\n")

    return "".join(out)


def _ident(name: str) -> str:
    return name.upper()


def _icon_module(names: list[str]) -> str:
    lines = ["pub mod icon {"]
    for i, n in enumerate(names):
        lines.append(f"    pub const {_ident(n)}: usize = {i};")
    lines.append(f"    pub const COUNT: usize = {len(names)};")
    lines.append("}\n")
    return "\n".join(lines)


def _effect_module(names: list[str]) -> str:
    lines = ["pub mod effect {"]
    for i, n in enumerate(names):
        lines.append(f"    pub const {_ident(n)}: usize = {i};")
    lines.append(f"    pub const COUNT: usize = {len(names)};")
    lines.append("}\n")
    return "\n".join(lines)


def _item_module(names: list[str]) -> str:
    lines = ["pub mod item {"]
    for i, n in enumerate(names):
        lines.append(f"    pub const {_ident(n)}: usize = {i};")
    lines.append(f"    pub const COUNT: usize = {len(names)};")
    lines.append("}\n")
    return "\n".join(lines)
