// Turns tests/fixtures/packed.json (spritekit dev-fixture: every sprite, packed the way the
// core stores it) into src/sprites.gen.ts so the design system ships the REAL art, never a
// redrawn copy. Keys are shortened: `species/lalafu/adult.txt::idle_a` -> `lalafu/adult/idle_a`,
// `global/icons.txt::feed` -> `icon/feed`, `global/font5x7.txt::a` -> `glyph/a`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "../../../tests/fixtures/packed.json");
const out = resolve(here, "../src/sprites.gen.ts");
const packed = JSON.parse(readFileSync(src, "utf8"));

const GLOBAL_PREFIX = {
  icons: "icon",
  items: "item",
  effects: "effect",
  hearts: "heart",
  font5x7: "glyph",
  egg: "egg",
  tombstone: "tombstone",
  hatch: "hatch",
};

function shortKey(key) {
  const [file, name] = key.split("::");
  const sp = /^species\/([^/]+)\/(\w+)\.txt$/.exec(file);
  if (sp) return `${sp[1]}/${sp[2]}/${name}`;
  const gl = /^global\/(\w+)\.txt$/.exec(file);
  if (gl) {
    const prefix = GLOBAL_PREFIX[gl[1]];
    if (!prefix) throw new Error(`unknown global file ${file}`);
    return gl[1] === "tombstone" ? "tombstone" : `${prefix}/${name}`;
  }
  throw new Error(`unrecognised sprite key ${key}`);
}

const entries = Object.entries(packed)
  .map(([k, v]) => [shortKey(k), { w: v.w, h: v.h, img: v.img, mask: v.mask ?? null }])
  .sort(([a], [b]) => (a < b ? -1 : 1));

const lines = [
  "// GENERATED by scripts/sprites.mjs from tests/fixtures/packed.json. Do not edit.",
  "import type { PackedSprite } from \"./packed\";",
  "",
  "export const SPRITES = {",
  ...entries.map(
    ([k, v]) =>
      `  ${JSON.stringify(k)}: { w: ${v.w}, h: ${v.h}, img: ${JSON.stringify(v.img)}, mask: ${
        v.mask ? JSON.stringify(v.mask) : "null"
      } },`,
  ),
  "} as const satisfies Record<string, PackedSprite>;",
  "",
  "export type SpriteName = keyof typeof SPRITES;",
  "",
];
writeFileSync(out, lines.join("\n"));
console.log(`sprites.gen.ts: ${entries.length} sprites`);
